### ISSUE TITLE
Add an option flag to skip CI

### ISSUE THREAD

**Issue by pecuchet** [pforret/setver#1]
It may useful to be able to append `[skip ci]` to the commit message. That way, test and/or build processes can be bypassed. (`[skip ci]` works both on Github and Bitbucket.)
Nice tool ;)

**Comment by pforret** [comment]
Good idea! I will add it soon.

**Comment by pforret** [comment]
check https://github.com/pforret/semver/releases/tag/v1.6.0 !

**Comment by pforret** [comment]
[skip ci] tested!
