### ISSUE TITLE
Two commits and git tag mismatch

### ISSUE THREAD

**Issue by pecuchet** [pforret/setver#10]
Hi @pforret, for repos with a package.json and a composer.json, two commits are created when using `setver new major/minor/patch`. The first one bumps the package.json and package-lock.json files, the second one the composer.json file. However only the first commit is tagged with the bumped version.

**Comment by pforret** [comment]
hi @pecuchet ,

I fixed it in version 2.2!

Peter

**Comment by pecuchet** [comment]
hi @pforret, thanks for that! However it now seems that setver does not commit the changes to `package-lock.json`:

```
❯ setver check
√  setver check versions:
√ Version in        git tag: 0.5.1
√ Version in  composer.json: 0.5.1
√ Version in   package.json: 0.5.1
√ Version in   .env.example: 0.5.1

❯ git diff package-lock.json
diff --git a/package-lock.json b/package-lock.json
index bead439..8c2b435 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -1,5 +1,5 @@
-    "version": "0.5.0",
+    "version": "0.5.1",
```

**Comment by pecuchet** [comment]
I don't think the version needs to be in the lock file btw....

**Comment by pforret** [comment]
> I don't think the version needs to be in the lock file btw....

It's npm that does this automatically. I've added package-lock.json to the git commit!
