### ISSUE TITLE
Dollar characters in .env

### ISSUE THREAD

**Issue by pecuchet** [pforret/setver#12]
The following happened on a new bare repo and with and `.env` containing a password with a `$` :
```
❯ setver new major
./.env: line 12: fkNIPHMO: unbound variable
× setver: ERROR 1 after 0 seconds 
> last command : 'source "$env_file"' 
${error_prefix} from line 1 : #!/usr/bin/env bash
```

**Comment by pforret** [comment]
This is a question I have been asking myself: can I just `source .env` or should I have a more complicated processing?
Your error is an example of why `source .env` can be too simplistic.
Quick fix (for you):
```
# don't use this
PASSWORD=ab$cdef
# but quote it
PASSWORD='as$cdef'
```

Better long-term solution (for me): no `source .env` but a dedicated `read_env_file` function.

**Comment by pforret** [comment]
fixed with the usage of the Os:clean_env function
