### ISSUE TITLE
Make git tag version prefix configurable

### ISSUE THREAD

**Issue by mlavi** [pforret/setver#6]
In function set_versions(), when [outputting the new version as a git tag](https://github.com/pforret/setver/blob/master/setver.sh#L480), a prefix "v" is hard-coded before the version. I've seen the convention many places, but I haven't adopted it [because any alphabetic character is a suffix](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions). It appears the v prefix is not used for any other output formats, which also seems inconsistent.

So my question/discussion becomes: can the hard coded v prefix become configurable or defeatable?

I could hack a simple PR fix for an environment variable to define the prefix if desired.

My ideal use case may not be the same for others, but I'd prefer the option! Interested in seeing if there are any other thoughts or what the origin/justification/convention is for the v prefix.

Thank you!

**Comment by pforret** [comment]
It's an easy enough feature, but it makes me regret not having based setver on bashew (it predates it a bit), because then it would have been super trivial to e.g. put the prefix you always use in the .env file (in your case `prefix=""`).

I'll keep the rewrite to bashew for a v2.0, but I will already add your feature!

**Comment by pforret** [comment]
Actually, it's a bit more complex. When you bump/set a version (e.g. "1.3.4") through npm, npm actually creates the git tag and **automatically adds the "v" prefix** (so "v1.3.4") . That was why I hardcoded it in setver, I assumed it was the standard procedure everywhere.

It should still work like you proposed for repos without package.json file.

**Comment by pforret** [comment]
Added to 1.15.0

**Comment by mlavi** [comment]
Thank you for the rapid response, really! You also answered my question about bashew. :)

I'll open a new issue since I've still not been able to get an unprefixed version into git tags yet with the latest release; I'll show how I tried to adopt (and failed).

**Comment by pforret** [comment]
Try the version 2.0.x! It also supports the .env files, so you can add a `prefix=""` line to your .env file

**Comment by mlavi** [comment]
Thank you!
