### ISSUE TITLE
setver -p option usage for empty prefix?

### ISSUE THREAD

**Issue by mlavi** [pforret/setver#9]
Thank you for #6 , I tried to make use of it today with setver v1.15.1 on GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu).

Here are all the ways I failed to get a plain semantic version into a git tag, my goal was to have a git tag of 0.0.1 without a "v" prefix. I made a file change in the repo between each attempt. I hope I'm missing something?

`echo '--seed' \
  && git tag -a -m 'seed' 0.0.1 \
  && git tag --list \
  && setver -v get # works
echo '--the following throw errors:'
setver -v -p get
setver -v -p '' get
echo '--make changes, add & commit, then bump patch'
git add --all && git commit -a -m 'patch: misc' \
  && setver new patch
\# [new tag]         0.0.1 -> 0.0.1
\# * [new tag]         v0.0.2 -> v0.0.2
\#---
\#  version 0.0.2 -> 0.0.3
\# * [new tag]         v0.0.3 -> v0.0.3

git add --all && git commit -a -m 'patch: -p args' && setver -p '' new patch
\# doesn't work

git add --all && git commit -a -m 'patch: -p args' && setver -p='' new patch
\# makes tag =0.0.4

git add --all && git commit -a -m 'patch: -p args' && setver -p'' new patch
\# ✖ : Don't understand action [patch]

git add --all && git commit -a -m 'patch: -p args' && OPTARG='' setver new patch
\#  * [new tag]         v0.0.5 -> v0.0.5

export OPTARG='' && git add --all && git commit -a -m 'patch: OPTARG' && setver new patch
\#  * [new tag]         v0.0.6 -> v0.0.6

export OPTARG='' && git add --all && git commit -a -m 'patch: OPTARG' && setver -p new patch
\# ✖ : Don't understand action [patch]
`

**Comment by pforret** [comment]
Thanks for your thorough testing! 
I went ahead and refactored `setver` to be based on the latest version of `bashew`.
It should work, except if you have a `package.json` file in your repo, then `npm` will force the `git tag` version to be in the "v9.9.9" format

**Comment by mlavi** [comment]
My test with `git add --all && git commit -a -m 'patch: setver2.0.2' && setver --prefix '' new patch` worked flawlessly, thank you!
